"""empty message

Revision ID: b7db714d049b
Revises: 
Create Date: 2025-11-11 18:43:55.206723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7db714d049b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('numero_transaccion', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mensaje', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mascota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('especie', sa.Enum('PERRO', 'GATO', 'OTRO', name='especiemascotaenum'), nullable=False),
    sa.Column('raza', sa.String(length=100), nullable=True),
    sa.Column('sexo', sa.Enum('MACHO', 'HEMBRA', name='sexomascotaenum'), nullable=False),
    sa.Column('estatus', sa.Enum('ADOPTADO', 'BUSCANDO_FAMILIA', name='estatusmascotaenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('genero', sa.Enum('MASCULINO', 'FEMENINO', 'OTRO', name='generousuarioenum'), nullable=False),
    sa.Column('correo_electronico', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'BANEADO', name='estatususuarioenum'), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'USUARIO', name='rolusuarioenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascota.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('numero_transaccion', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos')
    op.drop_table('favorito')
    op.drop_table('usuario')
    op.drop_table('mascota')
    op.drop_table('donaciones')
    # ### end Alembic commands ###
